export default {
	description: {
		shoppingCart: "购物车空空如也",
		loadFail: "加载失败",
		loading: "加载中",
		nullData: "空数据",
		permissionDenied: "无权限",
		noAgenda: "暂无日程",
		noPage: "页面不见了",
		noCoupon: "暂无优惠券",
		noData: "暂无数据",
		noCard: "暂无银行卡",
		noSignal: "暂无信号",
		noCollection: "暂无收藏",
		noNetwork: "无网络",
		noFolder: "文件夹空空如也",
		noSearch: "暂无搜索结果",
		noRecord: "暂无记录",
		slowNetwork: "网络不给力",
		noMessage: "暂无消息",
		directionless: "暂无方向",
		noHtml: "404"
	},
	descriptionColor: "#8c8c8c",
	primaryColor: "",
	clothingColor: "",
	otherColor: "",
}