export default {
	description: {
		shopping: "购物车空空如也",
		fail: "加载失败",
		loading: "加载中",
		null: "空数据",
		permission: "无权限",
		agenda: "暂无日程",
		page: "页面不见了",
		coupon: "暂无优惠券",
		data: "暂无数据",
		card: "暂无银行卡",
		signal: "暂无信号",
		collection: "暂无收藏",
		network: "无网络",
		folder: "文件夹空空如也",
		search: "暂无搜索结果",
		record: "暂无记录",
		slow: "网络不给力",
		message: "暂无消息",
		direction: "暂无方向",
		html: "404"
	},
	primaryColor: "primary",
	clothingColor: "warning",
	otherColor: "#141414",
}